version: "1.0"
language: "en-US"
reviews:
  enabled: true
  profile: "assertive" # Choices: chill, assertive, or comprehensive
  request_reviews_from_ai: true
  auto_review:version: "1.0"
language: "en-US"
reviews:
  enabled: true
  profile: "assertive"
  # NEW: Enable the high-level summary in the PR description
  high_level_summary: true
  # NEW: Enable sequence diagrams in the walkthrough
  sequence_diagrams: true
  # NEW: Include a summary of changed files
  changed_files_summary: true
  # NEW: Prevent the walkthrough from being hidden in a dropdown
  collapse_walkthrough: false
  
  request_reviews_from_ai: true
  auto_review:
    enabled: true
    ignore_paths:
      - "**/node_modules/**"
      - "**/dist/**"
      - "**/*.test.js"
    enabled: true
    ignore_paths:
      - "**/node_modules/**"
      - "**/dist/**"
      - "**/*.test.js"
