import type { Metadata } from "next";
import { Josefin_Slab } from "next/font/google";
import "./globals.css";

const josefinSlab = Josefin_Slab({
  variable: "--font-josefin-slab",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefinSlab.variable} antialiased`}>{children}</body>
    </html>
  );
}
